language: scala
scala:
   - 2.10.6
   - 2.11.8
jdk:
  - oraclejdk7
  - oraclejdk8
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler
script: "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"